// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBhza5kgGpuOvZRoU5ClRk5-KGl1O4L6Is',
    appId: '1:933552823747:web:b1efaf2e525de959e93176',
    messagingSenderId: '933552823747',
    projectId: 'prueba1appf',
    authDomain: 'prueba1appf.firebaseapp.com',
    storageBucket: 'prueba1appf.firebasestorage.app',
    measurementId: 'G-P3NMNX29YG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDBUUG1sIeaqdZXZ00xqm94b-xRfsCRM-g',
    appId: '1:933552823747:android:3fd61a7a4b3e593fe93176',
    messagingSenderId: '933552823747',
    projectId: 'prueba1appf',
    storageBucket: 'prueba1appf.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAEiUQ6i8u3Xqy7d9KHky0Z9QDIn7n76Ic',
    appId: '1:933552823747:ios:b6cf74515100e8ace93176',
    messagingSenderId: '933552823747',
    projectId: 'prueba1appf',
    storageBucket: 'prueba1appf.firebasestorage.app',
    iosBundleId: 'com.example.miMiniApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAEiUQ6i8u3Xqy7d9KHky0Z9QDIn7n76Ic',
    appId: '1:933552823747:ios:b6cf74515100e8ace93176',
    messagingSenderId: '933552823747',
    projectId: 'prueba1appf',
    storageBucket: 'prueba1appf.firebasestorage.app',
    iosBundleId: 'com.example.miMiniApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBhza5kgGpuOvZRoU5ClRk5-KGl1O4L6Is',
    appId: '1:933552823747:web:34a1571d9bdfc8f1e93176',
    messagingSenderId: '933552823747',
    projectId: 'prueba1appf',
    authDomain: 'prueba1appf.firebaseapp.com',
    storageBucket: 'prueba1appf.firebasestorage.app',
    measurementId: 'G-EMTLX71307',
  );

}