// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCwrR6DbmVHnXCBMpoGs5ZTOuCsoP8wpDc',
    appId: '1:290596582360:android:a082e93675a52ca24bf8ad',
    messagingSenderId: '290596582360',
    projectId: 'my-mini-app-2ac09',
    storageBucket: 'my-mini-app-2ac09.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDU4Ufsp0IqQ_Oht9q1OxbodtpH-mPZUQ8',
    appId: '1:290596582360:ios:f2e4ac11d4cae7b04bf8ad',
    messagingSenderId: '290596582360',
    projectId: 'my-mini-app-2ac09',
    storageBucket: 'my-mini-app-2ac09.firebasestorage.app',
    iosBundleId: 'com.example.myMiniApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB19uZC37iKP3snBcq7CkXzEAPNz7yPFJA',
    appId: '1:290596582360:web:1b99c41fc06f077b4bf8ad',
    messagingSenderId: '290596582360',
    projectId: 'my-mini-app-2ac09',
    authDomain: 'my-mini-app-2ac09.firebaseapp.com',
    storageBucket: 'my-mini-app-2ac09.firebasestorage.app',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB19uZC37iKP3snBcq7CkXzEAPNz7yPFJA',
    appId: '1:290596582360:web:1b99c41fc06f077b4bf8ad',
    messagingSenderId: '290596582360',
    projectId: 'my-mini-app-2ac09',
    authDomain: 'my-mini-app-2ac09.firebaseapp.com',
    storageBucket: 'my-mini-app-2ac09.firebasestorage.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDU4Ufsp0IqQ_Oht9q1OxbodtpH-mPZUQ8',
    appId: '1:290596582360:ios:f2e4ac11d4cae7b04bf8ad',
    messagingSenderId: '290596582360',
    projectId: 'my-mini-app-2ac09',
    storageBucket: 'my-mini-app-2ac09.firebasestorage.app',
    iosBundleId: 'com.example.myMiniApp',
  );

}